-- Insert PHQ-9 items
INSERT INTO ecoa_item (
  id, scaleId, itemNumber, question, questionEn, dimension, responseType, 
  responseOptions, scoringInfo, isRequired, sortOrder, createdAt, updatedAt, updateCounter
) VALUES
('item_phq9_01', 'scale_phq9', 1, '做事时提不起劲或没有兴趣', 'Little interest or pleasure in doing things', '核心症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_02', 'scale_phq9', 2, '感到心情低落、沮丧或绝望', 'Feeling down, depressed, or hopeless', '核心症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_03', 'scale_phq9', 3, '入睡困难、睡不安稳或睡眠过多', 'Trouble falling or staying asleep, or sleeping too much', '躯体症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_04', 'scale_phq9', 4, '感觉疲倦或没有活力', 'Feeling tired or having little energy', '躯体症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_05', 'scale_phq9', 5, '食欲不振或吃太多', 'Poor appetite or overeating', '躯体症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_06', 'scale_phq9', 6, '觉得自己很糟糕，或觉得自己很失败，或让自己或家人失望', 'Feeling bad about yourself - or that you are a failure or have let yourself or your family down', '认知症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_07', 'scale_phq9', 7, '对事物专注有困难，例如阅读报纸或看电视时', 'Trouble concentrating on things, such as reading the newspaper or watching television', '认知症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_08', 'scale_phq9', 8, '动作或说话速度缓慢到别人已经察觉？或正好相反—烦躁或坐立不安，动来动去的情况超过平常', 'Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual', '躯体症状', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('item_phq9_09', 'scale_phq9', 9, '有不如死掉或用某种方式伤害自己的想法', 'Thoughts that you would be better off dead, or of hurting yourself in some way', '自杀风险', 'likert', '["完全不会", "有几天", "一半以上的天数", "几乎每天"]', '0=完全不会, 1=有几天, 2=一半以上的天数, 3=几乎每天', 1, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);